### ISSUE TITLE
[BUG] When changing the PIN code

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/satochip_utils#24]
If I try to enter a PIN code that do NOT respect the security standard, there is a pop up saying that it does not meet the requirement. But then after, I have another pop up saying PIN Changed. 

![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/88d078f2-7e37-4db5-a778-a207096ba2a8)

If you work on this issue, please take note of the issue #19.

By the way, no need to spam the user with a pop up saying the PIN has been changed. 
When the user click on the button "Change it", the PIN code is changed and you redirect the user to the Home Page.

**Comment by Tech-Aware** [comment]
Normaly it's fixed ! thanks to close it if it's True !
