### ISSUE TITLE
[BUG] When trying to generate a new seedphrase

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/satochip_utils#26]
A pop up appears asking to copy past the seephrase. But there is no button to validate or go next.
Impossible to seed the Satochip.

![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/3082d5c9-5d74-49ec-a6f5-4a37d45fe6cf)

Please check issue #27 that might resolve this bug.

**Comment by Bastien-Satochip** [comment]
Bug is not fixed. 

It keeps saying the BIP39 checksum is not valid.

![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/2d42bfaa-67d2-4e2d-b72f-6dba9e9048a8)

![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/ae14cf34-c3c4-4b4c-93bf-bcc32dbe25c5)

Either with a 12 or 24 words, with or without adding a passphrase.



By the way, can you add a "back" button on these screens? So the user can even go back to the Home screen?

**Comment by Tech-Aware** [comment]
It is closed now ? It isn't ?
