### ISSUE TITLE
[BUG] I can get access to the "Change PIN" page even if I don't provide the PIN

### ISSUE THREAD

**Issue by Bastien-Satochip** [Tech-Aware/satochip_utils#28]
Setup: Seedkeeper card with a PIN code.

I plug the card and go to "Change PIN"
![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/19266126-14cc-4bd4-8d36-fd4fff3247b7)

A pop up appears to enter the PIN prior to access the change Pin page: OK
![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/f05679cb-8a36-46c4-99eb-7fe7e7f3c1fb)

I don't provide the PIN code and simply close the pop up... Another pop up appears.  
![image](https://github.com/Tech-Aware/satochip_utils/assets/87421384/a883645b-3a96-486f-b8ce-9b0f786a742d)

I click on OK... Then I have access to the "Change PIN page". 

No big deal... But as a user point of view, it feels like "I need the PIN code to able to change it"... But even if I don't provide it, I can have access to the "Change PIN page". 

To check.

**Comment by Toporin** [comment]
I don't think the 'enter PIN' popup is needed here since the Change PIN menu wizard request the old PIN already... No need to provide the same old PIN twice, so I would just removed the popup here.

**Comment by Tech-Aware** [comment]
> I don't think the 'enter PIN' popup is needed here since the Change PIN menu wizard request the old PIN already... No need to provide the same old PIN twice, so I would just removed the popup here.

Normaly it's closed.
