### ISSUE TITLE
Clean dependencies

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/satochip_utils#9]
Clean dependencies in requirements.txt:

* Check if these packages are really required:
** cashAddress, pycryptotools, pycryptodome, cryptography, eth_hash, pbkdf2
** use mnemonic v0.20 instead of v0.21 (for python 3.8 compatibility)

* clean imports in sources: many imports are not neeeded

* add pysatochip as a dependency rather than including its sources in code
** In principle you can use latest version available in Pypi: https://pypi.org/project/pysatochip/0.14.2/

**Comment by Tech-Aware** [comment]
Je suis sur le coup, mais quelques soucis sont apparau quand j'ai commencé à travailler sur cette issue. Car la librairie pystachip contient un CardConnector qui possède des méthodes différentes et les appels, pour certains, doivent être reveue en conséquence.

**Comment by Tech-Aware** [comment]
I add a new méthod [def check_authenticity()] inside CardConnector.py class CardConnector to get authenticity : but whit the CardConnector from Import Module and not from source code, but occur and error whith parse pem certificate.

here you have the stacktrace that didn't occur originaly in the hard code source. 

2024-05-22 06:12:32 - [controller.py:416] - INFO - controller - check_card_authenticity() - check_card_authenticity
2024-05-22 06:12:32 - [CardConnector.py:397] - INFO - pysatochip.CardConnector - card_verify_authenticity() - In card_verify_authenticity
2024-05-22 06:12:32 - [controller.py:327] - INFO - controller - PIN_dialog() - In PIN dialog
2024-05-22 06:12:32 - [controller.py:141] - INFO - controller - request() - get_passphrase
2024-05-22 06:12:38 - [CardConnector.py:403] - INFO - pysatochip.CardConnector - card_verify_authenticity() - Cert PEM: -----BEGIN CERTIFICATE-----
MIICCTCCAbCgAwIBAgIRAKMhKN61r8vAvZvC8P/T4WIwCgYIKoZIzj0EAwIwdDEL
MAkGA1UEBhMCQkUxETAPBgNVBAgMCEJydXNzZWxzMRAwDgYDVQQKDAdUb3Bvcmlu
MRMwEQYDVQQLDApTZWVkS2VlcGVyMSswKQYDVQQDDCJTZWVkS2VlcGVyIFBlcnNv
bmFsaXphdGlvbiBTdWJDQSAxMB4XDTIyMDkwMTAwMDAwMFoXDTQyMDkwMTAwMDAw
MFowejExMC8GA1UEAxMoOUNFMTI2MzUxREVCNjg5RkVENDRBMzAxNTFCNTExRTND
MzREQTQxQzETMBEGA1UECxMKU2VlZEtlZXBlcjEQMA4GA1UEChMHVG9wb3JpbjER
MA8GA1UECBMIQnJ1c3NlbHMxCzAJBgNVBAYTAkJFMFYwEAYHKoZIzj0CAQYFK4EE
AAoDQgAEMLNQQsC9zIzjI+WWtHcIghAEUsqQuqbDHdQK4sZ7Zf+LbLXS5txXMey/
4p+KQBbHxOYnXjXgEgFd5ixg2B7mKqMgMB4wDAYDVR0TAQH/BAIwADAOBgNVHQ8B
Af8EBAMCB4AwCgYIKoZIzj0EAwIDRwAwRAIgX6fQgGzMjhifyiKoFm4dsjvRFU5L
Q5F9DzY7pPJNOJ0CIBzP+aEGjwk1VsyfYWtGaIbkIUctFWcMtU27oVbD3ecc
-----END CERTIFICATE-----
2024-05-22 06:12:38 - [CardConnector.py:421] - INFO - pysatochip.CardConnector - card_verify_authenticity() - card_type = SeedKeeper
2024-05-22 06:12:38 - [CardConnector.py:422] - INFO - pysatochip.CardConnector - card_verify_authenticity() - is_valid_chain: True
2024-05-22 06:12:38 - [CardConnector.py:423] - INFO - pysatochip.CardConnector - card_verify_authenticity() - device_pubkey: b"\x040\xb3PB\xc0\xbd\xcc\x8c\xe3#\xe5\x96\xb4w\x08\x82\x10\x04R\xca\x90\xba\xa6\xc3\x1d\xd4\n\xe2\xc6{e\xff\x8bl\xb5\xd2\xe6\xdcW1\xec\xbf\xe2\x9f\x8a@\x16\xc7\xc4\xe6'^5\xe0\x12\x01]\xe6,`\xd8\x1e\xe6*"
2024-05-22 06:12:38 - [CardConnector.py:424] - INFO - pysatochip.CardConnector - card_verify_authenticity() - txt_ca: Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
        Signature Algorithm: ecdsa-with-SHA512
        Issuer: C=BE, ST=Brussels, O=Toporin, CN=Toporin Personalization Root CA 1
        Validity
            Not Before: Dec  1 12:00:00 2020 GMT
            Not After : Dec  1 12:00:00 2040 GMT
        Subject: C=BE, ST=Brussels, O=Toporin, CN=Toporin Personalization Root CA 1
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:e5:93:e0:79:0e:78:63:93:5d:4c:93:38:b9:85:
                    34:7f:eb:c3:2b:f0:f9:5c:8f:69:63:af:62:f8:49:
                    20:2b:89:7e:fb:32:a3:b0:63:18:63:b8:24:10:5c:
                    dc:a8:1d:67:41:19:fc:a3:3b:2c:ff:4b:d8:68:ca:
                    64:a1:e3:d8:36:a5:5d:d1:94:31:c0:57:1b:fc:d2:
                    c3:c9:94:2a:dc:dc:df:4c:09:90:8f:0e:8a:31:2b:
                    cf:2f:9e:d1:db:82:b5
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:1
            X509v3 Subject Key Identifier: 
                5D:6B:D1:DD:A2:AA:F9:94:7C:32:91:12:C1:82:42:15:9D:44:FA:21
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
    Signature Algorithm: ecdsa-with-SHA512
    Signature Value:
        30:65:02:31:00:94:c6:b6:e4:51:f5:c7:8d:a8:05:ee:e6:c0:
        0e:a7:ac:89:44:b7:67:8a:8e:d1:54:c9:88:65:62:e2:b2:13:
        e8:94:91:4d:f6:f3:ed:ec:54:81:0e:0c:51:9e:a5:09:57:02:
        30:5c:93:71:db:45:ed:24:99:7a:37:02:8b:7c:c2:0a:9d:fd:
        69:13:53:42:40:4a:d2:df:02:bd:94:b3:d9:92:be:ee:2b:f4:
        e9:ba:5a:ca:27:e8:5c:fb:5c:3b:f9:47:94

2024-05-22 06:12:38 - [CardConnector.py:425] - INFO - pysatochip.CardConnector - card_verify_authenticity() - txt_subca: Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: ecdsa-with-SHA512
        Issuer: C=BE, ST=Brussels, O=Toporin, CN=Toporin Personalization Root CA 1
        Validity
            Not Before: Dec  1 12:00:00 2020 GMT
            Not After : Dec  1 12:00:00 2040 GMT
        Subject: C=BE, ST=Brussels, O=Toporin, OU=SeedKeeper, CN=SeedKeeper Personalization SubCA 1
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:9a:5f:c4:f7:e9:bc:aa:21:55:2d:cc:69:af:27:
                    11:a3:4e:1b:7e:5e:af:44:16:12:12:cb:b3:37:58:
                    e2:c7:b5:d6:2d:d1:83:3e:58:84:ac:74:22:f8:b5:
                    35:6f:11:05:3a:73:61:f8:37:b1:0e:b2:eb:71:a2:
                    13:1a:bc:fa:c5
                ASN1 OID: secp256k1
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Subject Key Identifier: 
                9C:07:6B:E4:3D:87:8C:1D:41:D8:DF:45:B2:CF:0D:20:70:AE:F6:97
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
    Signature Algorithm: ecdsa-with-SHA512
    Signature Value:
        30:66:02:31:00:8f:ae:bb:c0:d9:85:38:db:2e:cf:c8:5b:c3:
        c7:e3:54:4e:9b:cf:14:1c:51:5e:34:3f:dd:4a:7e:c8:a1:db:
        0a:16:27:b5:0d:43:1e:16:29:f8:18:bc:18:87:5b:67:df:02:
        31:00:d7:0e:3b:6f:ed:46:97:a2:e0:36:be:ae:d2:d8:ad:3c:
        bd:96:d3:61:d0:1f:4f:fb:d5:cd:de:e0:20:e7:79:7b:c2:4d:
        f1:b5:e8:92:51:c6:d3:26:be:ff:91:75:3b:20

2024-05-22 06:12:38 - [CardConnector.py:426] - INFO - pysatochip.CardConnector - card_verify_authenticity() - txt_device: Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a3:21:28:de:b5:af:cb:c0:bd:9b:c2:f0:ff:d3:e1:62
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=BE, ST=Brussels, O=Toporin, OU=SeedKeeper, CN=SeedKeeper Personalization SubCA 1
        Validity
            Not Before: Sep  1 00:00:00 2022 GMT
            Not After : Sep  1 00:00:00 2042 GMT
        Subject: CN=9CE126351DEB689FED44A30151B511E3C34DA41C, OU=SeedKeeper, O=Toporin, ST=Brussels, C=BE
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:30:b3:50:42:c0:bd:cc:8c:e3:23:e5:96:b4:77:
                    08:82:10:04:52:ca:90:ba:a6:c3:1d:d4:0a:e2:c6:
                    7b:65:ff:8b:6c:b5:d2:e6:dc:57:31:ec:bf:e2:9f:
                    8a:40:16:c7:c4:e6:27:5e:35:e0:12:01:5d:e6:2c:
                    60:d8:1e:e6:2a
                ASN1 OID: secp256k1
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature
    Signature Algorithm: ecdsa-with-SHA256
    Signature Value:
        30:44:02:20:5f:a7:d0:80:6c:cc:8e:18:9f:ca:22:a8:16:6e:
        1d:b2:3b:d1:15:4e:4b:43:91:7d:0f:36:3b:a4:f2:4d:38:9d:
        02:20:1c:cf:f9:a1:06:8f:09:35:56:cc:9f:61:6b:46:68:86:
        e4:21:47:2d:15:67:0c:b5:4d:bb:a1:56:c3:dd:e7:1c

2024-05-22 06:12:38 - [CardConnector.py:427] - INFO - pysatochip.CardConnector - card_verify_authenticity() - txt_error: 
2024-05-22 06:12:38 - [CardConnector.py:433] - INFO - pysatochip.CardConnector - card_verify_authenticity() - is_valid_chalresp: True
2024-05-22 06:12:38 - [CardConnector.py:434] - INFO - pysatochip.CardConnector - card_verify_authenticity() - txt_error: 
2024-05-22 06:12:38 - [CardConnector.py:456] - ERROR - pysatochip.CardConnector - card_verify_authenticity() - An error occurred while verifying the device subject: 'CertificateValidator' object has no attribute 'parse_pem_certificate'

**Comment by Tech-Aware** [comment]
UPDATE :
I solved it adding some code into pysatochip library, into the CardConnector.py 

Adding line 102 in class RemovalObserver : a try/except block that get CPLC, IIN and CIN in order to create an unic UID_SHA1 for the card inserted.

According to this implementation into **RemovalObserver**, i add some necessary method into the **class CardConnector** : 

- def card_get_CPLC
- def card_get_IIN
- def card_get_CIN


Also used localy in check_verify_authenticity  an import to solve the issue about 'CertificateValidator' object parse_pem_certificate : 

from cryptography import x509
from cryptography.hazmat.backends import default backend

adding this and using it to parse the dict, permite to grant total access to certificate and validation that are necessary to permite to the user to checkt the certificate and verify the authenticity from a card into Satochip Utils.

**Comment by Tech-Aware** [comment]
CONTINUITY: 

IN the satochip_utils.exe, with the new update of pysatochip library in local, it's impossible to access certificate and validation. Probably due to that the official release of pysatochip library dont conatain the method that i add. Could @Toporin  confirm this hypothesis ?

**Comment by Tech-Aware** [comment]
> CONTINUITY:
> 
> IN the satochip_utils.exe, with the new update of pysatochip library in local, it's impossible to access certificate and validation. Probably due to that the official release of pysatochip library dont contain the method that i add. Could @Toporin confirm this hypothesis ?

SOLVED
